G_app/posts/routes.py
import sys
import json
from flask import render_template, url_for, flash, redirect, request, jsonify, abort, Blueprint
from wtforms import RadioField
from G_app.posts.forms import PostForm, PostFormGeneral, ChallengeForm, EditChallengeForm, BetForm, EditBetForm
from G_app.models import User, Post, Challenge, Bet
from G_app import db, scheduler
from flask_login import current_user, login_required
from G_app.posts.utils import *
from datetime import datetime, timedelta

posts = Blueprint('posts', __name__)

'''
def add_post():
    post = Post(title='shit dawg', content='scheduler is working!', id_user=1)
    db.session.add(post)
    db.session.commit()
'''
#scheduler.add_job(func=add_post, trigger='date', run_date=datetime(2019,1,16,0,34,30), id='test')


@posts.context_processor
def context_processor():
    chug = chug_matrix()
    members=member_ls()
    return dict(chug_matrix=chug, members=members)


@posts.route("/post_rating", methods=['POST'])
def post_rating():
    rating = request.form.get('rating')
    post_id = request.form.get('post_id')
    post_id = int(post_id)
    rating = int(rating)
    post_num_voted = number_voted(post_id)
    post = Post.query.filter_by(id=int(post_id)).first()
    new_rating = ((post.rating * post_num_voted) + rating)/(post_num_voted + 1)
    post.rating = new_rating
    if post.voted:
        post.voted += '\n'+current_user.username
    else:
        post.voted = current_user.username
    db.session.commit()
    return jsonify({"message" : "Rating: {} | Post ID: {} | data: {}".format(rating, post_id, type(post_id)),
                    "rating" : round(new_rating, 2)})


@posts.route("/delete_post", methods=['POST'])
def delete_post():
    post_id = request.form.get('post_id')
    post = Post.query.get_or_404(int(post_id))
    delete_post_notifications(post)
    db.session.delete(post)
    db.session.commit()
    return jsonify({"message" : "Successfully deleted post"})


@posts.route("/edit/post/id/<post_id>", methods=['GET','POST'])
@login_required
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    if post.type != 'General':
        form = PostForm()
    else:
        form = PostFormGeneral()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data, 'static/post_pics', 500, 500)
            post.image = picture_file
        post.title = form.title.data
        post.content = form.content.data
        if post.type != "General":
            id_target = User.query.filter_by(username=form.target.data).first().id
            post.id_target = id_target
        db.session.commit()
        flash("Your post has been updated!", 'success')
        return redirect(url_for('main.home'))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
        if post.type != "General":
            form.target.data = post.target.username
    return render_template('update_post.html', form=form, post_type=post.type)



@posts.route("/new/post/<post_type>", methods=['GET', 'POST'])
@login_required
def new_post(post_type):
    if not post_type in ['General', 'Request']:
        setattr(PostForm, 'target', RadioField('Choose Target', choices=get_choices()))
        form = PostForm()
    else:
        form = PostFormGeneral()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data, 'static/post_pics', 500, 500)
        else:
            picture_file = None
        if post_type == 'General':
            post = Post(title=form.title.data, content=form.content.data, id_user=current_user.id, image=picture_file)
        else:
            if post_type == 'Request':
                id_target = current_user.id
            else:
                id_target = User.query.filter_by(username=form.target.data).first().id
            post = Post(title=form.title.data, content=form.content.data, type=post_type, rating=0, can_vote=True, image=picture_file, id_user=current_user.id, id_target=id_target)
        db.session.add(post)
        db.session.commit()
        create_post_notifications(post)
        flash("Your post has been created!", 'success')
        return redirect(url_for('main.home'))
        #post = Post(title=form.title.data, content=form.content.data)
        #if form.picture.data:
            #picture_file = save_picture(form.picture.data, 'static/post_pics')
    #if form.validate_on_submit():
        #flash("Your post has been created!", 'success')
        #return redirect(url_for('main.home'))
    return render_template('create_post.html', form=form, post_type=post_type)



@posts.route("/bet_completed", methods=["POST"])
@login_required
def bet_completed():
    bet_id = json.loads(request.form.get('bet_id'))
    is_verification = json.loads(request.form.get('is_verification'))
    bet_won = json.loads(request.form.get('bet_won'))
    bet = Bet.query.get_or_404(bet_id)
    if is_verification:
        bet.won = bet_won
        bet.active = False
        bet.finish_notification()
        bet.finish_post()
        if bet.won:
            amount = bet.odds*bet.amount - bet.amount
            bet.bookmaker.transfer(recipient=bet.bettaker, amount=amount, title="Bet transfer")
        else:
            bet.bettaker.transfer(recipient=bet.bookmaker, amount=bet.amount, title="Bet transfer")
    else:
        bet.win_claim = True
        content = "{} claims to have won the bet '{}'".format(bet.bettaker.username, bet.title)
        link = url_for('posts.my_bets')
        bet.bookmaker.notification(title="BET WIN CLAIM", content=content, link=link)
    return jsonify({ 'content' : 'success' })




@posts.route("/new/bet", methods=['GET', 'POST'])
@login_required
def new_bet():
    choices = get_choices()
    choices.append(('anyone', 'Anyone'))
    setattr(BetForm, 'target', RadioField('Choose Target', choices=choices))
    form = BetForm()
    if form.validate_on_submit():
        if form.target.data != 'anyone':
            target_id = User.query.filter_by(username=form.target.data).first().id
        else:
            target_id = None
        title = form.title.data
        description = form.description.data
        amount = form.amount.data
        odds = form.odds.data
        bet = Bet(title=title, description=description, amount=amount, odds=odds, id_bookmaker=current_user.id, id_bettaker=target_id)
        db.session.add(bet)
        db.session.commit()
        bet.create_post()
        bet.create_notification()
        flash("Successfully created bet", 'success')
        return redirect(url_for('main.home'))
    return render_template('new_bet.html', form=form)



@posts.route("/edit/bet/id/<int:bet_id>", methods=['GET', 'POST'])
@login_required
def edit_bet(bet_id):
    bet = Bet.query.get_or_404(bet_id)
    if bet.accepted_by_bookmaker and bet.accepted_by_bettaker or\
    current_user not in {bet.bettaker, bet.bookmaker} or\
    current_user == bet.bookmaker and bet.accepted_by_bookmaker or\
    current_user == bet.bettaker and bet.accepted_by_bettaker or\
    not bet.active:
        abort(403)
    form = EditBetForm()
    if form.validate_on_submit():
        if bet.description == form.description.data and bet.amount == form.amount.data and bet.odds == form.odds.data:
            bet.accepted_by_bettaker = True
            bet.accepted_by_bookmaker = True
            bet.accept_post()
            bet.accept_notification()
            flash("The bet has been accepted successfully", 'success')
        else:
            bet.description = form.description.data
            bet.amount = form.amount.data
            bet.odds = form.odds.data
            bet.accepted_by_bettaker = not bet.accepted_by_bettaker
            bet.accepted_by_bookmaker = not bet.accepted_by_bookmaker
            bet.modify_post()
            bet.modify_notification()
            flash("Modified bet", 'success')
        return redirect(url_for('main.home'))
    elif request.method == 'POST':
        key = request.form.get('delete_key')
        if key == "D3l3t3":
            bet.active = False
            db.session.commit()
        flash("Bet refused", 'danger')
    elif request.method == 'GET':
        form.description.data = bet.description
        form.amount.data = bet.amount
        form.odds.data = bet.odds
    return render_template('edit_bet.html', form=form, bet=bet)



@posts.route("/available_bets", methods=['GET','POST'])
@login_required
def available_bets():
    bets = Bet.query.filter(Bet.bettaker==None, Bet.bookmaker!=current_user).all()
    if request.method == 'POST':
        user_id = request.form.get('user_id')
        bet_id = request.form.get('bet_id')
        user = User.query.get(user_id)
        bet = Bet.query.get(bet_id)
        bet.bettaker = user
        bet.accepted_by_bettaker = True
        db.session.commit()
        bet.accept_post(was_public=True)
        bet.accept_notification(was_public=True)
        return jsonify({ 'user' : user.username, 'bet' : bet.title })
    return render_template('available_bets.html', bets=bets)



@posts.route("/my_bets")
@posts.route("/my_bets/page_m=<int:page_m>/page_t=<int:page_t>")
@login_required
def my_bets(page_m=1, page_t=1):
    bets_made = Bet.query.filter_by(id_bookmaker=current_user.id).order_by(Bet.date.desc()).paginate(page=page_m, per_page=5)
    bets_target = Bet.query.filter_by(id_bettaker=current_user.id).order_by(Bet.date.desc()).paginate(page=page_t, per_page=5)
    bets_pending, bets_active = pending_active_bets(current_user.bets_made + current_user.bets_taken)
    return render_template('my_bets.html', bets_made=bets_made, bets_target=bets_target, bets_pending=bets_pending, bets_active=bets_active)



@posts.route("/all_bets")
@login_required
def all_bets():
    page = request.args.get('page', 1, type=int)
    bets = Bet.query.order_by(Bet.date.desc()).paginate(page=page, per_page=10)

G_app/users/routes.py
import json
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint, jsonify
from G_app.users.forms import LoginForm, UpdateForm, RequestResetForm, ResetPasswordForm
from G_app.models import User, Post, Chug, Groceries
from G_app import db, bcrypt, mail, scheduler
from flask_login import login_user, current_user, logout_user, login_required
from G_app.users.utils import *
from datetime import datetime, timedelta

users = Blueprint('users', __name__)


@users.context_processor
def context_processor():
    chug = chug_matrix()
    members=member_ls()
    return dict(chug_matrix=chug, members=members)



@users.route("/login", methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash("Login not successful. Check email and password.", 'danger')
    return render_template('login.html', title='Login', form=form)



@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))



@users.route("/user/<username>")
@login_required
def profile(username):
    user = User.query.filter_by(username=username).first()
    if user:
        user_image = url_for('static', filename="profile_pics/{}".format(user.image))
        return render_template('profile.html', user=user, user_image=user_image, chug_price=chug_price())
    else:
        return abort(404)



@users.route("/account", methods=['GET','POST'])
@login_required
def account():
    form = UpdateForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data, 'static/profile_pics', 150, 150)
            if current_user.image != 'default.jpg':
                delete_old_picture()
            current_user.image = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Account information has been updated!", 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    user_image = url_for('static', filename="profile_pics/{}".format(current_user.image))
    return render_template('account.html', title='Account', user_image=user_image, form=form)



@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect('home')
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("An email has been sent with reset instructions.", 'info')
        return redirect(url_for('users.login'))
    return render_template('request_reset.html', form=form)



@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect('home')
    user = User.verify_reset_token(token)
    if not user:
        flash("Invalid or expired token.", 'danger')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data)
        user.password = hashed_password
        db.session.commit()
        flash("Your password has been updated!", 'success')
        return redirect('login')
    return render_template('reset_token.html', form=form)



@users.route("/current_user_id")
@login_required
def current_user_id():
    return jsonify({'id':current_user.id})



@users.route("/update_status/id/<user_id>", methods=['POST'])
def update_status(user_id):
    user = User.query.get_or_404(user_id)
    status = request.form.get('status')
    user.status = status.capitalize()
    db.session.commit()
    return ""



@users.route("/give_chug", methods=['POST'])
def give_chug():
    recipient_id = request.form.get('recipient_id')
    giver_id = request.form.get('giver_id')
    recipient = User.query.get(recipient_id)
    giver = User.query.get(giver_id)
    title = "{} gives {} a chug".format(giver.username, recipient.username)
    chug = Chug(title=title, id_taker=recipient_id, id_giver=giver_id)
    db.session.add(chug)
    db.session.commit()
    giver.deduct(chug_price())
    accept_by_date = datetime.now() + timedelta(seconds=30)
    scheduler.add_job(func=accept_chug, args=[chug.id], trigger='date', run_date=accept_by_date, id='chug'+str(chug.id))
    chug.create_notification()
    return jsonify({ 'content' : 'success' })



@users.route("/respond_chug", methods=['POST'])
def respond_chug():
    chug_id = request.form.get('chug_id')
    accept = json.loads(request.form.get('accept'))
    scheduler.remove_job('chug'+str(chug_id))
    chug = Chug.query.get(chug_id)
    chug.accepted = accept
    if not accept:
        chug.taker.deduct(chug_price())
        chug.active = False
    chug.accept_notification()
    db.session.commit()
    return jsonify({ 'content' : chug.title })



@users.route("/decrease_chug", methods=['POST'])
def decrease_chug():
    id_giver = request.form.get('id_giver')
    id_taker = request.form.get('id_taker')
    chug = Chug.query.filter(Chug.id_taker==id_taker, Chug.id_giver==id_giver, Chug.active==True, Chug.accepted==True).first()
    chug.active = False
    chug.taken = True
    db.session.commit()
    return jsonify({ 'content' : chug.id })



@users.route("/chug/id/<int:chug_id>")
@login_required
def chug(chug_id):
    chug = Chug.query.get_or_404(chug_id)
    return render_template('chug.html', chug=chug, chug_price=chug_price())

G_app/templates/about.html
<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
  $("#hide").click(function(){
    $("p").hide();
  });
  $("#show").click(function(){
    $("p").show();
  });
});
</script>
</head>
<body>

<p>If you click on the "Hide" button, I will disappear.</p>

<button id="hide">Hide</button>
<button id="show">Show</button>

</body>
</html>

G_app/templates/home.html
{% extends "layout.html" %}

  {% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/post_rate.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/delete_post.js') }}"></script>
  {% endblock %}


  {% block home_active %}
    "nav-item active"
  {% endblock %}

  {% block content %}
    {% if current_user.is_authenticated %}

      <div class="row" style="margin-top:10px">
        <h3 class="ml-3">Posts</h3>
        <div class="btn-group ml-auto mr-3">
          <a role="button" href="{{ url_for('posts.new_post', post_type='Mess') }}" class="btn btn-outline-danger">Mess</a>
          <a role="button" href="{{ url_for('posts.new_post', post_type='Punish') }}" class="btn btn-outline-warning">Punish</a>
          <a role="button" href="{{ url_for('posts.new_post', post_type='General') }}" class="btn btn-outline-info">General</a>
          <a role="button" href="{{ url_for('posts.new_post', post_type='Request') }}" class="btn btn-outline-success">Request</a>
          <div class="btn-group">
            <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown">Challenge</button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{{ url_for('posts.new_challenge') }}">Create challenge</a>
              <a class="dropdown-item" href="{{ url_for('posts.my_challenges') }}">My challenges</a>
              <a class="dropdown-item" href="{{ url_for('posts.all_challenges') }}">All challenges</a>
            </div>
          </div>
          <div class="btn-group">
            <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown">Bet</button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{{ url_for('posts.new_bet') }}">Create bet</a>
              <a class="dropdown-item" href="{{ url_for('posts.my_bets') }}">My bets</a>
              <a class="dropdown-item" href="{{ url_for('posts.available_bets') }}">Available bets</a>
              <a class="dropdown-item" href="{{ url_for('posts.all_bets') }}">All bets</a>
            </div>
          </div>
        </div>
      </div>
      <hr>
      {% for post in posts.items %}
        <div class="media" id="{{ 'post' + post.id|string }}">
          <img class="rounded-circle account-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image) }}" alt="user_image">
          <div class="media-body">
            <div class="post-section">
              <h6 id="{{ post.type }}">{{ post.type }}</h6>
              {% if post.author == current_user %}
                <a href="{{ url_for('posts.edit_post', post_id = post.id) }}">
                  <h5 class="border-bottom border-secondary" style="padding-bottom:2px">{{ post.title }}{{ " -- Target: " + post.target.username if post.target }}</h5>
                </a>
              {% else %}
                <h5 class="border-bottom border-secondary" style="padding-bottom:2px">{{ post.title }}{{ " -- Target: " + post.target.username if post.target }}</h5>
              {% endif %}
              <p>
              {% for line in post.content.splitlines() %}
                {{ line }}<br>
              {% endfor %}
              </p>
              {% if post.image %}
                <img src="{{ url_for('static', filename='post_pics/' + post.image) }}" height="200">
              {% endif %}
              <hr>
              {% if post.can_vote and current_user.username not in voters[post.id] and current_user.id != post.id_target %}
                <div class="row">
                  <div class="col-sm-3">
                    <p id="rate{{ post.id }}">Rate severity:</p>
                  </div>
                  <div class="col-sm-9">
                    <form class="rate-form" id="{{ post.id }}">
                      <label class="radio-inline ml-2" for="1">1</label>
                      <input type="radio" name="{{ 'rating' + post.id|string }}" value=1>
                      <label class="radio-inline ml-2" for="2">2</label>
                      <input type="radio" name="{{ 'rating' + post.id|string }}" value=2>
                      <label class="radio-inline ml-2" for="3">3</label>
                      <input type="radio" name="{{ 'rating' + post.id|string }}" value=3>
                      <label class="radio-inline ml-2" for="4">4</label>
                      <input type="radio" name="{{ 'rating' + post.id|string }}" value=4>
                      <label class="radio-inline ml-2" for="5">5</label>
                      <input type="radio" name="{{ 'rating' + post.id|string }}" value=5>
                      <button type="submit" id="sbtn">Submit</button>
                    </form>
                  </div>
                  <div class="vote-alert" id="{{ 'alert' + post.id|string }}" style="display:none;">
                    <p class="success" id="{{ 'rating' + post.id|string }}"></p>
                  </div>
                  <small style="margin-left:15px" id="{{ 'msg' + post.id|string }}">The current rating will be revealed once you have rated.</small>
                </div>
              {% elif post.rating %}
                <div class="row">
                  <div class="col-sm-3">
                    <p>Rating:</p>
                  </div>
                  <div class="col-sm-9">
                    <p>{{ post.rating|round(2) }}/5</p>
                  </div>
                </div>
              {% endif %}
              <div class="row">
                <small class="ml-3 pt-2">By <a href="{{ url_for('users.profile', username=post.author.username) }}">{{ post.author.username }}</a> on {{ post.date_posted.date() }}</small>
                {% if post.author == current_user %}
                  <button type="button" id="{{ post.id }}" class="delbtn btn btn-outline-danger ml-auto mr-3">Delete</button>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
      <div class="modal fade" id="deleteModal">
        <div class="modal-dialog">
          <div class="modal-content">

            <div class="modal-header">
              <h5>Are you sure?</h5>
            </div>

            <div class="modal-body">
              Deleting this post cannot be undone. Please make an informed decision!
            </div>

            <div class="modal-footer">
              <button type="button" class="btn btn-outline-primary" id="closeModal">Close</button>
              <button type="button" class="deletePost btn btn-danger" id="">Delete</button>
            </div>

          </div>
        </div>
      </div>
      <div class="row mt-2 mb-2">
        <div class="col-12" align="center">
          {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
              {% if posts.page == page_num %}
                <a class="btn btn-secondary ml-1 mr-1" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
              {% else %}
                <a class="btn btn-outline-secondary ml-1 mr-1" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
              {% endif %}
            {% else %}
              ...
            {% endif %}
          {% endfor %}
        </div>
      </div>
    {% else %}
      <h4 style='margin-top:10px'>Uh oh, It looks like somebody is not logged in...</h4>
      <hr>
      <small>If you have an account, please log in to gain full access to this wonderful site. If you are not a member, then that is unfortunate, for you will not be able to gain access!</small>
    {% endif %}

  {% endblock %}

G_app/templates/my_bets.html
{% extends "layout.html" %}

  {% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/bet_complete.js') }}"></script>
  {% endblock %}

  {% block content %}
    {% if bets_active %}
      <h3 class="mt-1">Active bets</h3>
      {% for bet in bets_active %}
        <div class="bet-section {{ 'bet' + bet.id|string }} mt-2" id="green">
          <div class="row">
            <div class="col-9 divider-right">
                <h5>{{ bet.title }} | for {{ bet.amount }}.00 ₲</h5>
                <p>
                {% for line in bet.description.splitlines() %}
                  {{ line }}<br>
                {% endfor %}
                </p>
            </div>
            <div class="col-3 my-auto" align="center">
              {% if not bet.win_claim %}
                {% if current_user == bet.bettaker %}
                  <div id="{{ 'claimMsg' + bet.id|string }}" style="display:none;">
                    <p class="success">Let's hope your claim is accepted!</p>
                  </div>
                  <button type="button" class="winBtn btn btn-outline-light" id="{{ bet.id }}" onclick="showWinModal('{{ bet.description }}', {{ bet.id }})">Won?</button>
                {% elif current_user == bet.bookmaker %}
                  <p>Waiting for {{ bet.bettaker.username }} to make a win claim</p>
                {% endif %}
              {% else %}
                {% if current_user == bet.bettaker %}
                  <p>Waiting for {{ bet.bookmaker.username }} to verify your claim</p>
                {% elif current_user == bet.bookmaker %}
                  <button type="button" class="verifyBtn btn btn-outline-light" onclick="showVerifyModal({{ bet.id }}, '{{ bet.bettaker.username }}')">Verify</button>
                {% endif %}
              {% endif %}
            </div>
          </div>
        </div>
      {% endfor %}
    {% endif %}
    <hr>
    {% if bets_pending %}
      <h3 class="mt-3">Bets pending</h3>
      {% for bet in bets_pending %}
        {% if current_user == bet.bookmaker %}
          {% set color = 'blue' %}
        {% else %}
          {% set color = 'pink' %}
        {% endif %}
        <div class="bet-section mt-2" id="{{ color }}">
          <div class="row">
            <div class="col-9 divider-right">
              <h5>{{ bet.title }} | for {{ bet.amount }}.00 ₲</h5>
              <p>
              {% for line in bet.description.splitlines() %}
                {{ line }}<br>
              {% endfor %}
              </p>
            </div>
            <div class="col-3 my-auto" align="center">
              {% if ( (current_user == bet.bookmaker and bet.accepted_by_challenger) or
                      (current_user == bet.bettaker and bet.accepted_by_challengee) )%}
                <p>Waiting for response</p>
              {% else %}
                <a role="button" class="btn btn-outline-light" href="{{ url_for('posts.edit_bet', bet_id=bet.id) }}">Please respond</a>
              {% endif %}
            </div>
          </div>
        </div>
      {% endfor %}
    {% endif %}
    {% if not bets_made.items and not bets_target.items %}
      <p>You have not made or received any bets...</p>
    {% endif %}
    <hr>
    <div class="row mt-3">
      <div class="col-md-6">
        {% if bets_made.items %}
          <h3>Bets made</h3>
          {% for bet in bets_made.items %}
            <div class="bet-section mt-2" id="{{ 'green' if bet in bets_active else 'blue'}}">
              <h5>{{ bet.title }} | for {{ bet.amount }}.00 ₲</h5>
              <p>
              {% for line in bet.description.splitlines() %}
                {{ line }}<br>
              {% endfor %}
              </p>
            </div>
          {% endfor %}
        {% endif %}
        <div class="row mt-1">
          <div class="col-12" align="center">
            {% for page_num in bets_made.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
              {% if page_num %}
                {% if bets_made.page == page_num %}
                  <a class="btn btn-secondary ml-1 mr-1 mb-1" href="{{ url_for('posts.my_challenges', page_m=page_num, page_t=bets_target.page) }}">{{ page_num }}</a>
                {% else %}
                  <a class="btn btn-outline-secondary ml-1 mr-1 mb-1" href="{{ url_for('posts.my_challenges', page_m=page_num, page_t=bets_target.page) }}">{{ page_num }}</a>
                {% endif %}
              {% else %}
                ...
              {% endif %}
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="col-md-6">
        {% if bets_target.items %}
          <h3>Bets received</h3>
          {% for bet in bets_target.items %}
            <div class="bet-section mt-2" id="{{ 'green' if bet in bets_active else 'pink'}}">
              <h5>{{ bet.title }} | for {{ bet.amount }}.00 ₲</h5>
              <p>
              {% for line in bet.description.splitlines() %}
                {{ line }}<br>
              {% endfor %}
              </p>
            </div>
          {% endfor %}
        {% endif %}
        <div class="row mt-1">
          <div class="col-12" align="center">
            {% for page_num in bets_target.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
              {% if page_num %}
                {% if bets_target.page == page_num %}
                  <a class="btn btn-secondary ml-1 mr-1 mb-1" href="{{ url_for('posts.my_challenges', page_t=page_num, page_m=bets_made.page) }}">{{ page_num }}</a>
                {% else %}
                  <a class="btn btn-outline-secondary ml-1 mr-1 mb-1" href="{{ url_for('posts.my_challenges', page_t=page_num, page_m=bets_made.page) }}">{{ page_num }}</a>
                {% endif %}
              {% else %}
                ...
              {% endif %}
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
    <div class="modal fade claimModal">
      <div class="modal-dialog">
        <div class="modal-content">

          <div class="modal-header">
            <h5>Did you win the bet?</h5>
          </div>

          <div class="modal-body">
            <span class="winModalBody" style="white-space: pre-wrap">

            </span>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-outline-primary" onclick="closeModal('claim')">Close</button>
            <button type="button" class="winClaim btn btn-success" id="">Won</button>
            <button type="button" class="lostBet btn btn-danger" id="">Lost</button>
          </div>

        </div>
      </div>
    </div>
    <div class="modal fade verifyModal">
      <div class="modal-dialog">
        <div class="modal-content">

          <div class="modal-header">
            <h5>Please verify</h5>
          </div>

          <div class="modal-body verifyModalBody">

          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-outline-primary" onclick="closeModal('verify')">Close</button>
            <button type="button" class="verifyWin btn btn-success" id="">Verify</button>
            <button type="button" class="refuseClaim btn btn-danger" id="">Refuse</button>
          </div>

        </div>
      </div>
    </div>


  {% endblock %}